config/routes.rb
ArtsbyIronhack::Application.routes.draw do
 
  devise_for :users
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :paintings, only: [:create, :destroy, :new, :index, :show] do
    resources :comments, only: [:create]
  end
  
  root :to => "homes#home"

  get '/help' => "homes#help"
  get '/about' => "homes#about"

  
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
  belongs_to :painting

end

app/models/comments.rb
class Comment < ActiveRecord::Base
	belongs_to :user
  belongs_to :events

end

app/models/painting.rb
class Painting < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
	belongs_to :user
	has_many :comments
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id", class_name:  "Relationship", dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  has_many :paintings, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
  #validates :name, presence: true
  
  #validates :email, presence: true

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) << :name
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    #@comment = Comment.new(params[:comment])
 	@painting = Painting.find(params[:painting_id])

 	@comment = @painting.comments.build comment_params
 	@comment.user = current_user
 	
    if @comment.save
      redirect_to @painting, notice: "Comment added"
    else
      redirect_to @painting, alert: "Comment not added :("
    end
  end

  private
  def comment_params
  	params.require(:comment).permit(:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	
	def home
		if user_signed_in?
			@user = current_user
			@followers = @user.followers
			render :home_user
		else
			render :home
		end
	end
	
  def help
  end

  def about
  end

end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
 #before_action :correct_user,   only: :destroy

  def index
  	@paintings = Painting.all
  end

  def new
  	@painting = Painting.new
  end

  def show
  	@painting = Painting.find(params[:id])
    @painting.user = current_user
  end

  def create
  	@painting = Painting.new(painting_params)
    @painting.user = current_user

  	if @painting.save
  		redirect_to @painting, notice: "You have upload #{@painting.name} succesfully"
  	else
  		render "new"
  	end
  end

  def destroy
  	@painting = Painting.find(params[:id])

  	@painting.destroy
  	redirect_to :back
  end

  private

  def painting_params
  	params.require(:painting).permit(:name, :description, :picture, :filename, :tempfile, :original_filename)
  end
  
  #def correct_user
   # @painting = current_user.paintings.find_by(id: params[:id])
   # redirect_to painting_url if @painting.nil?
  #end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
 #before_action :signed_in_use

  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#before_action :signed_in_user, only: [:edit, :update]
	#before_action :correct_user,   only: [:edit, :update]

  def index 
		@users = User.all
	end

	def show
    @user = User.find(params[:id])
    @paintings = @user.paintings
  end

  def edit
  	@user = User.find(params[:id])
    @paintings = @user.paintings
  end

  def update
  	@user = User.find(params[:id])

    if @user.update edit_params
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    #@users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    #@users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private
  def edit_params
  	params.require(:user).permit(:name, :email, :password)
  end

  #def signed_in_user
   # redirect_to signin_url, notice: "Please sign in." unless signed_in?
  #end

  #def correct_user
    #@user = User.find(params[:id])
    #redirect_to(root_url) unless current_user?(@user)
  #end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	#def current_user?(user)
  #  user == current_user
  #end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
	def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  	end
end

app/views/homes/_topbar.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Artsby</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="has-dropdown">
        <a href="#">Profile</a>
        <ul class="dropdown">
          <li><a <%= link_to "Log Out", destroy_user_session_path, method: :delete %></a></li>
        </ul>
      </li>
    </ul>
       <!-- Left Nav Section -->
    <ul class="left">
      <li><a <%= link_to "Home", users_path %></a></li>
    </ul>
  </section>
</nav>

app/views/homes/home.about.html.erb
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>About Us</title>
</head>
<body>
	<h1>About Us</h1>
	<p>Artsby busca poner el arte al alcance de todo el mundo, para que la gente pueda disfrutar de esta magnifica....</p>
</body>
</html>

app/views/homes/home.html.erb
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Artsby App Webpage</title>
</head>
<body>
	<%= render partial: 'topbar' %>
	<h1>Artsby App</h1>
	<p>Acabas de entrar en un portal dedicado exclusivamente al arte, antes de poder acceder a el tendras que registrarte</p>
	<a class= "button" <%= link_to "Registrate", new_user_registration_path %> </a>
	
	<a class= "button" <%= link_to "Sign in", new_session_path(:user) %> </a>
</body>
</html>

app/views/homes/home_help.html.erb
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Help</title>
</head>
<body>
	<h1>Help Area</h1>
	<p>Ante cualquier duda, escribenos a info@artsby.com</p>
</body>
</html>

app/views/homes/home_user.html.erb
hola usuario
<div>
<section>
<%= gravatar_for @user %>
<%= @user.name %>
<%= @user.email %>
<%= link_to "Edit", edit_user_path(@user) %>
</section>
<div class="stats">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
</div>
<div class="followers">
	<ul>
		<% @followers.each do |follower| %>
		<li><%= follower.name %></li>
		<!--<li><%= follower.email %></li>-->
		<% end %>
	</ul>
<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Artsby" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/paintings/create.html.erb
<h1>Paintings#create</h1>
<p>Find me in app/views/paintings/create.html.erb</p>

app/views/paintings/destroy.html.erb
<h1>Paintings#destroy</h1>
<p>Find me in app/views/paintings/destroy.html.erb</p>

app/views/paintings/index.html.erb
	<% @paintings.each do |painting| %>
     <%= link_to (image_tag painting.picture_url.to_s, painting_path)%>
	<% end %>

app/views/paintings/new.html.erb
<%= form_for @painting, :html => { multipart: true } do |f| %>
<% if @painting.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @painting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
 
<div class="well">
  
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.label :picture %>
    <%= f.file_field :picture %>
    <%= f.submit "Save" %>
  <% end %>
</div>

app/views/paintings/show.html.erb
<div class="painting">
<%= image_tag @painting.picture_url %>

</div>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/static_pages/about.html.erb
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>About Us</title>
</head>
<body>
	<h1>About Us</h1>
	<p>Artsby busca poner el arte al alcance de todo el mundo, para que la gente pueda disfrutar de esta magnifica....</p>
</body>
</html>

app/views/static_pages/help.html.erb
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Help</title>
</head>
<body>
	<h1>Help Area</h1>
	<p>Ante cualquier duda, escribenos a info@artsby.com</p>
</body>
</html>

app/views/static_pages/home.html.erb
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Artsby App Webpage</title>
</head>
<body>
	<h1>Artsby App</h1>
	<p>Acabas de entrar en un portal dedicado exclusivamente al arte, antes de poder acceder a el tendras que registrarte</p>
	<%=link_to "Registrate", new_user_registration_path %>
</body>
</html>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow" %>
<% end %>

app/views/users/_follow_form.html.erb
<%# unless current_user?(@user) %>
  
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<%# end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow" %>
<% end %>

app/views/users/edit.html.erb
<div>
<section>
<%= gravatar_for @user %>
<%= @user.name %>
<%= @user.email %>
</section>
<div class="stats">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
</div>
<p>
  <% @paintings.each do |painting| %>
  <%= image_tag painting.picture_url %>
  <%= link_to "Edit", paintings_path(painting) %>
  <%= link_to "Delete", painting, method: :delete %>
  <% end %>
  <br>
  <%= link_to "Upload", new_painting_path %>
	<%= link_to "Log out", destroy_user_session_path, method: :delete %>
</p>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>Todos los Usuarios</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div>
<section>
<%= gravatar_for @user %>
<%= @user.name %>
<%= @user.email %>
</section>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
  <div>
    <%= render 'follow_form' if signed_in? %>
  </div>
</div>
  <% @paintings.each do |painting| %>
  <%= image_tag painting.picture_url %>
  <%= form_for [painting, Comment.new] do |f| %>
    <div class="field">
      <%= f.label :body, "Comment" %><br>
      <%= f.text_area :body %>
    </div>
      <%= f.submit "Comment!" %> 
    <% end %>
  <% end %>